name: Cadnano2

on:
  push:
    branches:
        - master
        - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller pillow
        python setup.py install
        if exist requirements.txt pip install -r requirements.txt
        python -m pip uninstall -y PyQt6-sip
        python -m pip install PyQt6-sip
      shell: cmd
    - name: build-bundle
      run: |
        pyinstaller cadnano.spec
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: cadnano-windows
        path: dist/cadnano.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller pillow
        python setup.py install
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build-bundle
      run: |
        pyinstaller cadnano.spec
    - uses: actions/upload-artifact@v3
      with:
        name: cadnano-linux
        path: dist/cadnano

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller pillow
        python setup.py install
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build-bundle
      run: |
        pyinstaller cadnano.spec
    - uses: actions/upload-artifact@v3
      with:
        name: cadnano-macos
        path: dist/cadnano

  publish:
    runs-on: ubuntu-latest
    needs: [build-win, build-linux, build-macos]
    steps:
    - uses: actions/checkout@v3
    - name: Download builds
      uses: actions/download-artifact@v3
      with:
        path: "."
    - name: Display structure of downloaded files
      run: ls -R
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.GITHUB_REF || github.event.head_commit.message }}
        name: ${{ github.event.head_commit.message }}
