name: Cadnano2

on:
  push:
    branches:
        - master
        - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build-bundle
      run: |
        pyinstaller cadnano.spec
        mv dist/cadnano dist/cadnano-linux
    - uses: actions/upload-artifact@v3
      with:
        name: cadnano-linux
        path: dist/cadnano-linux
